/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a BasePluginDBusAdaptor -c BasePluginDBusAdaptor com.buteo.msyncd.baseplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef BASEPLUGINDBUSADAPTOR_H_1381687227
#define BASEPLUGINDBUSADAPTOR_H_1381687227

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.buteo.msyncd.baseplugin
 */
class BasePluginDBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.buteo.msyncd.baseplugin")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.buteo.msyncd.baseplugin\">\n"
"    <signal name=\"transferProgress\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aTransferDatabase\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aTransferType\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMimeType\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aCommittedItems\"/>\n"
"    </signal>\n"
"    <signal name=\"error\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMessage\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aErrorCode\"/>\n"
"    </signal>\n"
"    <signal name=\"success\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMessage\"/>\n"
"    </signal>\n"
"    <signal name=\"acquiredStorage\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMimeType\"/>\n"
"    </signal>\n"
"    <signal name=\"syncProgressDetail\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aProgressDetail\"/>\n"
"    </signal>\n"
"    <method name=\"getPluginName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getProfileName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"init\"/>\n"
"    <method name=\"uninit\"/>\n"
"    <method name=\"abortSync\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"aStatus\"/>\n"
"    </method>\n"
"    <method name=\"cleanUp\"/>\n"
"    <method name=\"getSyncResults\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"connectivityStateChanged\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"aType\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"aState\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    BasePluginDBusAdaptor(QObject *parent);
    virtual ~BasePluginDBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void abortSync(uchar aStatus);
    void cleanUp();
    void connectivityStateChanged(int aType, int aState);
    QString getPluginName();
    QString getProfileName();
    QString getSyncResults();
    void init();
    void uninit();
Q_SIGNALS: // SIGNALS
    void acquiredStorage(const QString &aMimeType);
    void error(const QString &aProfileName, const QString &aMessage, int aErrorCode);
    void success(const QString &aProfileName, const QString &aMessage);
    void syncProgressDetail(const QString &aProfileName, int aProgressDetail);
    void transferProgress(const QString &aProfileName, int aTransferDatabase, int aTransferType, const QString &aMimeType, int aCommittedItems);
};

#endif
