/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a BasePluginDBusAdaptor -c BasePluginDBusAdaptor com.buteo.msyncd.baseplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "BasePluginDBusAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class BasePluginDBusAdaptor
 */

BasePluginDBusAdaptor::BasePluginDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

BasePluginDBusAdaptor::~BasePluginDBusAdaptor()
{
    // destructor
}

void BasePluginDBusAdaptor::abortSync(uchar aStatus)
{
    // handle method call com.buteo.msyncd.baseplugin.abortSync
    QMetaObject::invokeMethod(parent(), "abortSync", Q_ARG(uchar, aStatus));
}

void BasePluginDBusAdaptor::cleanUp()
{
    // handle method call com.buteo.msyncd.baseplugin.cleanUp
    QMetaObject::invokeMethod(parent(), "cleanUp");
}

void BasePluginDBusAdaptor::connectivityStateChanged(int aType, int aState)
{
    // handle method call com.buteo.msyncd.baseplugin.connectivityStateChanged
    QMetaObject::invokeMethod(parent(), "connectivityStateChanged", Q_ARG(int, aType), Q_ARG(int, aState));
}

QString BasePluginDBusAdaptor::getPluginName()
{
    // handle method call com.buteo.msyncd.baseplugin.getPluginName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getPluginName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString BasePluginDBusAdaptor::getProfileName()
{
    // handle method call com.buteo.msyncd.baseplugin.getProfileName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getProfileName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString BasePluginDBusAdaptor::getSyncResults()
{
    // handle method call com.buteo.msyncd.baseplugin.getSyncResults
    QString out0;
    QMetaObject::invokeMethod(parent(), "getSyncResults", Q_RETURN_ARG(QString, out0));
    return out0;
}

void BasePluginDBusAdaptor::init()
{
    // handle method call com.buteo.msyncd.baseplugin.init
    QMetaObject::invokeMethod(parent(), "init");
}

void BasePluginDBusAdaptor::uninit()
{
    // handle method call com.buteo.msyncd.baseplugin.uninit
    QMetaObject::invokeMethod(parent(), "uninit");
}

