/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ButeoPluginIfAdaptor -a ButeoPluginIfAdaptor.h:ButeoPluginIfAdaptor.cpp com.buteo.msyncd.baseplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ButeoPluginIfAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ButeoPluginIfAdaptor
 */

ButeoPluginIfAdaptor::ButeoPluginIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ButeoPluginIfAdaptor::~ButeoPluginIfAdaptor()
{
    // destructor
}

void ButeoPluginIfAdaptor::abortSync(uchar aStatus)
{
    // handle method call com.buteo.msyncd.baseplugin.abortSync
    QMetaObject::invokeMethod(parent(), "abortSync", Q_ARG(uchar, aStatus));
}

bool ButeoPluginIfAdaptor::cleanUp()
{
    // handle method call com.buteo.msyncd.baseplugin.cleanUp
    bool out0;
    QMetaObject::invokeMethod(parent(), "cleanUp", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ButeoPluginIfAdaptor::connectivityStateChanged(int aType, bool aState)
{
    // handle method call com.buteo.msyncd.baseplugin.connectivityStateChanged
    QMetaObject::invokeMethod(parent(), "connectivityStateChanged", Q_ARG(int, aType), Q_ARG(bool, aState));
}

QString ButeoPluginIfAdaptor::getPluginName()
{
    // handle method call com.buteo.msyncd.baseplugin.getPluginName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getPluginName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString ButeoPluginIfAdaptor::getProfileName()
{
    // handle method call com.buteo.msyncd.baseplugin.getProfileName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getProfileName", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString ButeoPluginIfAdaptor::getSyncResults()
{
    // handle method call com.buteo.msyncd.baseplugin.getSyncResults
    QString out0;
    QMetaObject::invokeMethod(parent(), "getSyncResults", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool ButeoPluginIfAdaptor::init()
{
    // handle method call com.buteo.msyncd.baseplugin.init
    bool out0;
    QMetaObject::invokeMethod(parent(), "init", Q_RETURN_ARG(bool, out0));
    return out0;
}

QString ButeoPluginIfAdaptor::profile()
{
    // handle method call com.buteo.msyncd.baseplugin.profile
    QString out0;
    QMetaObject::invokeMethod(parent(), "profile", Q_RETURN_ARG(QString, out0));
    return out0;
}

void ButeoPluginIfAdaptor::resume()
{
    // handle method call com.buteo.msyncd.baseplugin.resume
    QMetaObject::invokeMethod(parent(), "resume");
}

void ButeoPluginIfAdaptor::setPluginParams(const QString &aPluginName, const QString &aProfile)
{
    // handle method call com.buteo.msyncd.baseplugin.setPluginParams
    QMetaObject::invokeMethod(parent(), "setPluginParams", Q_ARG(QString, aPluginName), Q_ARG(QString, aProfile));
}

bool ButeoPluginIfAdaptor::startListen()
{
    // handle method call com.buteo.msyncd.baseplugin.startListen
    bool out0;
    QMetaObject::invokeMethod(parent(), "startListen", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool ButeoPluginIfAdaptor::startSync()
{
    // handle method call com.buteo.msyncd.baseplugin.startSync
    bool out0;
    QMetaObject::invokeMethod(parent(), "startSync", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ButeoPluginIfAdaptor::stopListen()
{
    // handle method call com.buteo.msyncd.baseplugin.stopListen
    QMetaObject::invokeMethod(parent(), "stopListen");
}

void ButeoPluginIfAdaptor::suspend()
{
    // handle method call com.buteo.msyncd.baseplugin.suspend
    QMetaObject::invokeMethod(parent(), "suspend");
}

bool ButeoPluginIfAdaptor::uninit()
{
    // handle method call com.buteo.msyncd.baseplugin.uninit
    bool out0;
    QMetaObject::invokeMethod(parent(), "uninit", Q_RETURN_ARG(bool, out0));
    return out0;
}

