/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ButeoPluginIfAdaptor -a ButeoPluginIfAdaptor.h:ButeoPluginIfAdaptor.cpp com.buteo.msyncd.baseplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef BUTEOPLUGINIFADAPTOR_H_1383027885
#define BUTEOPLUGINIFADAPTOR_H_1383027885

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.buteo.msyncd.baseplugin
 */
class ButeoPluginIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.buteo.msyncd.baseplugin")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.buteo.msyncd.baseplugin\">\n"
"    <!-- BEGIN: Common plugin methods -->\n"
"    <signal name=\"transferProgress\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aTransferDatabase\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aTransferType\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMimeType\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aCommittedItems\"/>\n"
"    </signal>\n"
"    <signal name=\"error\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMessage\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aErrorCode\"/>\n"
"    </signal>\n"
"    <signal name=\"success\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMessage\"/>\n"
"    </signal>\n"
"    <signal name=\"accquiredStorage\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aMimeType\"/>\n"
"    </signal>\n"
"    <signal name=\"syncProgressDetail\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aProfileName\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"aProgressDetail\"/>\n"
"    </signal>\n"
"    <method name=\"setPluginParams\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"aPluginName\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"aProfile\"/>\n"
"    </method>\n"
"    <method name=\"getPluginName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"getProfileName\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"init\"/>\n"
"    <method name=\"uninit\"/>\n"
"    <method name=\"abortSync\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"aStatus\"/>\n"
"    </method>\n"
"    <method name=\"cleanUp\"/>\n"
"    <method name=\"getSyncResults\">\n"
"      <!-- We will pass the SyncResults as an XML string and use constructor and toXml to perform serialization/deserialization -->\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"connectivityStateChanged\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"aType\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"aState\"/>\n"
"    </method>\n"
"    <!-- END: Common plugin methods -->\n"
"    <!-- BEGIN: Client plugin methods -->\n"
"    <method name=\"startSync\"/>\n"
"    <method name=\"profile\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <!-- We will pass the SyncResults as an XML string and use constructor and toXml to perform serialization/deserialization -->\n"
"    </method>\n"
"    <!-- END: Client plugin methods -->\n"
"    <!-- BEGIN: Server plugin methods -->\n"
"    <signal name=\"newSession\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aDestination\"/>\n"
"    </signal>\n"
"    <method name=\"startListen\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"stopListen\"/>\n"
"    <method name=\"suspend\"/>\n"
"    <method name=\"resume\"/>\n"
"    <!-- END: Server plugin methods -->\n"
"  </interface>\n"
        "")
public:
    ButeoPluginIfAdaptor(QObject *parent);
    virtual ~ButeoPluginIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void abortSync(uchar aStatus);
    void cleanUp();
    void connectivityStateChanged(int aType, int aState);
    QString getPluginName();
    QString getProfileName();
    QString getSyncResults();
    void init();
    QString profile();
    void resume();
    void setPluginParams(const QString &aPluginName, const QString &aProfile);
    bool startListen();
    void startSync();
    void stopListen();
    void suspend();
    void uninit();
Q_SIGNALS: // SIGNALS
    void accquiredStorage(const QString &aMimeType);
    void error(const QString &aProfileName, const QString &aMessage, int aErrorCode);
    void newSession(const QString &aDestination);
    void success(const QString &aProfileName, const QString &aMessage);
    void syncProgressDetail(const QString &aProfileName, int aProgressDetail);
    void transferProgress(const QString &aProfileName, int aTransferDatabase, int aTransferType, const QString &aMimeType, int aCommittedItems);
};

#endif
