/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ButeoPluginIfaceAdaptor -a ButeoPluginIfaceAdaptor.h:ButeoPluginIfaceAdaptor.cpp com.buteo.msyncd.baseplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ButeoPluginIfaceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ButeoPluginIfaceAdaptor
 */

ButeoPluginIfaceAdaptor::ButeoPluginIfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ButeoPluginIfaceAdaptor::~ButeoPluginIfaceAdaptor()
{
    // destructor
}

void ButeoPluginIfaceAdaptor::abortSync(uchar aStatus)
{
    // handle method call com.buteo.msyncd.baseplugin.abortSync
    QMetaObject::invokeMethod(parent(), "abortSync", Q_ARG(uchar, aStatus));
}

bool ButeoPluginIfaceAdaptor::cleanUp()
{
    // handle method call com.buteo.msyncd.baseplugin.cleanUp
    bool out0;
    QMetaObject::invokeMethod(parent(), "cleanUp", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ButeoPluginIfaceAdaptor::connectivityStateChanged(int aType, bool aState)
{
    // handle method call com.buteo.msyncd.baseplugin.connectivityStateChanged
    QMetaObject::invokeMethod(parent(), "connectivityStateChanged", Q_ARG(int, aType), Q_ARG(bool, aState));
}

QString ButeoPluginIfaceAdaptor::getSyncResults()
{
    // handle method call com.buteo.msyncd.baseplugin.getSyncResults
    QString out0;
    QMetaObject::invokeMethod(parent(), "getSyncResults", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool ButeoPluginIfaceAdaptor::init()
{
    // handle method call com.buteo.msyncd.baseplugin.init
    bool out0;
    QMetaObject::invokeMethod(parent(), "init", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ButeoPluginIfaceAdaptor::resume()
{
    // handle method call com.buteo.msyncd.baseplugin.resume
    QMetaObject::invokeMethod(parent(), "resume");
}

bool ButeoPluginIfaceAdaptor::startListen()
{
    // handle method call com.buteo.msyncd.baseplugin.startListen
    bool out0;
    QMetaObject::invokeMethod(parent(), "startListen", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool ButeoPluginIfaceAdaptor::startSync()
{
    // handle method call com.buteo.msyncd.baseplugin.startSync
    bool out0;
    QMetaObject::invokeMethod(parent(), "startSync", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ButeoPluginIfaceAdaptor::stopListen()
{
    // handle method call com.buteo.msyncd.baseplugin.stopListen
    QMetaObject::invokeMethod(parent(), "stopListen");
}

void ButeoPluginIfaceAdaptor::suspend()
{
    // handle method call com.buteo.msyncd.baseplugin.suspend
    QMetaObject::invokeMethod(parent(), "suspend");
}

bool ButeoPluginIfaceAdaptor::uninit()
{
    // handle method call com.buteo.msyncd.baseplugin.uninit
    bool out0;
    QMetaObject::invokeMethod(parent(), "uninit", Q_RETURN_ARG(bool, out0));
    return out0;
}

