/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ClientPluginDBusAdaptor -c ClientPluginDBusAdaptor com.buteo.msyncd.clientplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ClientPluginDBusAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ClientPluginDBusAdaptor
 */

ClientPluginDBusAdaptor::ClientPluginDBusAdaptor(QObject *parent)
    : BasePluginDBusAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ClientPluginDBusAdaptor::~ClientPluginDBusAdaptor()
{
    // destructor
}

QString ClientPluginDBusAdaptor::profile()
{
    // handle method call com.buteo.msyncd.clientplugin.profile
    QString out0;
    QMetaObject::invokeMethod(parent(), "profile", Q_RETURN_ARG(QString, out0));
    return out0;
}

void ClientPluginDBusAdaptor::startSync()
{
    // handle method call com.buteo.msyncd.clientplugin.startSync
    QMetaObject::invokeMethod(parent(), "startSync");
}

