/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ClientPluginDBusAdaptor -c ClientPluginDBusAdaptor com.buteo.msyncd.clientplugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CLIENTPLUGINDBUSADAPTOR_H_1381687264
#define CLIENTPLUGINDBUSADAPTOR_H_1381687264

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "BasePluginDBusAdaptor.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.buteo.msyncd.clientplugin
 */
class ClientPluginDBusAdaptor: public BasePluginDBusAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.buteo.msyncd.clientplugin")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.buteo.msyncd.clientplugin\">\n"
"    <method name=\"startSync\"/>\n"
"    <method name=\"profile\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ClientPluginDBusAdaptor(QObject *parent);
    virtual ~ClientPluginDBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString profile();
    void startSync();
Q_SIGNALS: // SIGNALS
};

#endif
