/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ServerPluginDBusAdaptor -c ServerPluginDBusAdaptor com.buteo.msyncd.serverplugin.xml -l BasePluginDBusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ServerPluginDBusAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerPluginDBusAdaptor
 */

ServerPluginDBusAdaptor::ServerPluginDBusAdaptor(BasePluginDBusAdaptor *parent)
    : BasePluginDBusAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerPluginDBusAdaptor::~ServerPluginDBusAdaptor()
{
    // destructor
}

void ServerPluginDBusAdaptor::resume()
{
    // handle method call com.buteo.msyncd.serverplugin.resume
    QMetaObject::invokeMethod(parent(), "resume");
}

bool ServerPluginDBusAdaptor::startListen()
{
    // handle method call com.buteo.msyncd.serverplugin.startListen
    bool out0;
    QMetaObject::invokeMethod(parent(), "startListen", Q_RETURN_ARG(bool, out0));
    return out0;
}

void ServerPluginDBusAdaptor::stopListen()
{
    // handle method call com.buteo.msyncd.serverplugin.stopListen
    QMetaObject::invokeMethod(parent(), "stopListen");
}

void ServerPluginDBusAdaptor::suspend()
{
    // handle method call com.buteo.msyncd.serverplugin.suspend
    QMetaObject::invokeMethod(parent(), "suspend");
}

