/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ServerPluginDBusAdaptor -c ServerPluginDBusAdaptor com.buteo.msyncd.serverplugin.xml -l BasePluginDBusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVERPLUGINDBUSADAPTOR_H_1381687341
#define SERVERPLUGINDBUSADAPTOR_H_1381687341

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "BasePluginDBusAdaptor.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.buteo.msyncd.serverplugin
 */
class ServerPluginDBusAdaptor: public BasePluginDBusAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.buteo.msyncd.serverplugin")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.buteo.msyncd.serverplugin\">\n"
"    <signal name=\"newSession\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"aDestination\"/>\n"
"    </signal>\n"
"    <method name=\"startListen\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"stopListen\"/>\n"
"    <method name=\"suspend\"/>\n"
"    <method name=\"resume\"/>\n"
"  </interface>\n"
        "")
public:
    ServerPluginDBusAdaptor(BasePluginDBusAdaptor *parent);
    virtual ~ServerPluginDBusAdaptor();

    inline BasePluginDBusAdaptor *parent() const
    { return static_cast<BasePluginDBusAdaptor *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void resume();
    bool startListen();
    void stopListen();
    void suspend();
Q_SIGNALS: // SIGNALS
    void newSession(const QString &aDestination);
};

#endif
