#!/bin/sh

DEF_UID=$(grep "^UID_MIN" /etc/login.defs |  tr -s " " | cut -d " " -f2)
DEVICEUSER=$(getent passwd $DEF_UID | sed 's/:.*//')
if [ ! -d "/home/$DEVICEUSER/.cache" ]; then
    exit 1
fi
storage_dir="/home/$DEVICEUSER/.cache/msyncd"
mkdir -p $storage_dir
chown privileged $storage_dir
chgrp privileged $storage_dir
chmod 770 $storage_dir

sync_dir="/home/$DEVICEUSER/.cache/msyncd/sync"
mkdir -p $sync_dir
chown privileged $sync_dir
chgrp privileged $sync_dir
chmod 770 $sync_dir

